### ISSUE TITLE
Could not fetch version info

### ISSUE THREAD

**Issue by francoisph** [arfeo/npm-add-dependencies#8] opened 2019-11-19 16:36 UTC
Hey,

I'm trying to use your plugin. After a npm install -g npm-add-dependencies I run in my project :
`npm-add-dependencies git+https://github.com/arfeo/npm-add-dependencies.git#master --dev`

And I've got this  : 
`This script adds dependencies (latest or specified versions) to the package.json file without installing them
Adding packages to 'devDependencies'...
Could not fetch version info for: git+https://github.com/arfeo/npm-add-dependencies.git#master. Skip.
Done.`

Any ideas ?
Thanks :)

**Comment by arfeo** [comment] 2019-11-19 16:40
Hi,

Tried just now:
![image](https://user-images.githubusercontent.com/11537376/69166519-6b86ea00-0b04-11ea-9bfa-e3bf0a6da341.png)

Need more info to make any decision.

Thanks.

**Comment by francoisph** [comment] 2019-11-19 16:46
Thanks for the fast response!
This is what I've got when trying the example in the README : 
<img width="774" alt="Capture d’écran, le 2019-11-19 à 11 43 45" src="https://user-images.githubusercontent.com/4134881/69166965-1c1fca00-0ac2-11ea-99c4-051e605674f0.png">

**Comment by arfeo** [comment] 2019-11-19 16:48
Any additional info for me to deal with? Have fetched packages been written to the `package.json` successfully, e.g.? ANY info, pls. So, I could reproduce the error. Thanks.

**Comment by arfeo** [comment] 2019-11-19 16:50
What is this command's output:

```npm show git+https://github.com/arfeo/npm-add-dependencies.git#master versions```

?

**Comment by francoisph** [comment] 2019-11-19 16:58
When I'm cloning your git and run the command inside your project everything works. 

When I run npm show git+https://github.com/arfeo/npm-add-dependencies.git#master versions  in my project I have this : 

<img width="638" alt="Capture d’écran, le 2019-11-19 à 11 57 20" src="https://user-images.githubusercontent.com/4134881/69167951-c3e9c780-0ac3-11ea-9249-158c69ba069a.png">

And the log : 

<img width="1339" alt="Capture d’écran, le 2019-11-19 à 11 55 11" src="https://user-images.githubusercontent.com/4134881/69167984-d06e2000-0ac3-11ea-995b-f755b4888238.png">

**Comment by arfeo** [comment] 2019-11-19 17:09
Have fetched packages been written to the `package.json` successfully? Looks like the error with the `package.json` in your project's directory. Looks like there's no one. Strange enough, because in this case the script should output this: "Could not parse package.json. Stop." and stop.

**Comment by francoisph** [comment] 2019-11-19 17:15
Yes I can fetch all the packages in the package.json.
When I run in my project  : 
`npm install git+https://github.com/arfeo/npm-add-dependencies.git#master --save` 

My package is correctly updated : 
`"npm-add-dependencies": "git+https://github.com/arfeo/npm-add-dependencies.git#master",`

**Comment by arfeo** [comment] 2019-11-19 17:17
No, I meant, have fetched packages been written to the package.json successfully after this:

![image](https://user-images.githubusercontent.com/11537376/69169512-860f9200-0b09-11ea-8243-f76a2b499c6d.png)
?

**Comment by arfeo** [comment] 2019-11-19 17:29
I think there's no way at the moment to fetch the info of a package with "git+https". I removed this from readme, and I'll think it over some time later. Thanks for this.

**Comment by arfeo** [comment] 2019-11-19 17:34
NB: We can not use `npm show git+https://github.com/author/repo#branch versions` to fetch repo's versions.

**Comment by francoisph** [comment] 2019-11-19 18:32
Okay thanks for the information!

**Comment by arfeo** [comment] 2019-12-28 19:35
Closing the issue, since it most probably wouldn't be fixed.

**Closed as completed by arfeo** 2019-12-28 19:35 UTC
Labels: enhancement, wontfix
